### PR TITLE
Set a ptex/<version> user agent.

### PR DESCRIPTION
**Pull request by jsirois**
This is good form and needed to access api.github.com / not get 403'd.

### CODE REVIEW

**Comment by jsirois** [comment]
It's a bit of a long story, but it turns out - as IndyGreg notes well in a quirks section of the docs for PythonBuildStandalone - that the Pythons he ships probably won't work for building C extensions due to hard coded paths from his deployment containers leaking into sysconfig. Combine that with Pants use of `psutil` / `setproctitle` and the like ... and my enemy, macOS (arm in particular), and `pip install pantsbuild.pants` can fail. Even though we'll start releasing Pants scies or at least single platform PEXes, in the meantime I'd still like scie-pants to work. As such I use the trick of always turning --find-links towards binaries.pantsbuild.org like we currently do just for the PANTS_SHA case. This works great ... except for a 403 using api.github.com to translate release tag names (Pants versions) to shas.

**Comment by jsirois** [comment]
I'm going to shuffle this one along to get a clean scie-pants test on macOS.

**Review by benjyw — COMMENTED** [review]
LGTM

**Comment by sureshjoshi** [comment]
What a strange Github requirement. 

Adding link if needed later: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#user-agent-required

> This allows us to contact you if there are problems

... alright... I guess it's assuming there are good faith problems, like an app that accidentally goes out of control and bypasses a rate limit? 🤷🏽

**Pull request merged**
